import { ReactComponent } from './../../../../src/types/svg.d';
export { ReactComponent as UpIcon } from './up.svg';
export { ReactComponent as DownIcon } from './down.svg';
export { ReactComponent as LeftIcon } from './left.svg';
export { ReactComponent as RightIcon } from './right.svg';
export { ReactComponent as ChevronUpIcon } from './chevron-up.svg';
export { ReactComponent as ChevronDownIcon } from './chevron-down.svg';
export { ReactComponent as ChevronLeftIcon } from './chevron-left.svg';
export { ReactComponent as ChevronRightIcon } from './chevron-right.svg';
export { ReactComponent as TooltipTopArrowIcon } from './tooltip-top-arrow.svg';
export { ReactComponent as TooltipBottomArrowIcon } from './tooltip-bottom-arrow.svg';
