const flags = [
  { country: 'AFGHANISTAN', flag: '🇦🇫' },
  { country: 'ÅLAND_ISLANDS', flag: '🇦🇽' },
  { country: 'ALBANIA', flag: '🇦🇱' },
  { country: 'ALGERIA', flag: '🇩🇿' },
  { country: 'AMERICAN_SAMOA', flag: '🇦🇸' },
  { country: 'ANDORRA', flag: '🇦🇩' },
  { country: 'ANGOLA', flag: '🇦🇴' },
  { country: 'ANGUILLA', flag: '🇦🇮' },
  { country: 'ANTARCTICA', flag: '🇦🇶' },
  { country: 'ANTIGUA_AND_BARBUDA', flag: '🇦🇬' },
  { country: 'ARGENTINA', flag: '🇦🇷' },
  { country: 'ARMENIA', flag: '🇦🇲' },
  { country: 'ARUBA', flag: '🇦🇼' },
  { country: 'AUSTRALIA', flag: '🇦🇺' },
  { country: 'AUSTRIA', flag: '🇦🇹' },
  { country: 'AZERBAIJAN', flag: '🇦🇿' },
  { country: 'BAHAMAS', flag: '🇧🇸' },
  { country: 'BAHRAIN', flag: '🇧🇭' },
  { country: 'BANGLADESH', flag: '🇧🇩' },
  { country: 'BARBADOS', flag: '🇧🇧' },
  { country: 'BELARUS', flag: '🇧🇾' },
  { country: 'BELGIUM', flag: '🇧🇪' },
  { country: 'BELIZE', flag: '🇧🇿' },
  { country: 'BENIN', flag: '🇧🇯' },
  { country: 'BERMUDA', flag: '🇧🇲' },
  { country: 'BHUTAN', flag: '🇧🇹' },
  { country: 'BOLIVIA', flag: '🇧🇴' },
  { country: 'BOSNIA_AND_HERZEGOVINA', flag: '🇧🇦' },
  { country: 'BOTSWANA', flag: '🇧🇼' },
  { country: 'BRAZIL', flag: '🇧🇷' },
  { country: 'BRITISH_INDIAN_OCEAN_TERRITORY', flag: '🇮🇴' },
  { country: 'BRITISH_VIRGIN_ISLANDS', flag: '🇻🇬' },
  { country: 'BRUNEI', flag: '🇧🇳' },
  { country: 'BULGARIA', flag: '🇧🇬' },
  { country: 'BURKINA_FASO', flag: '🇧🇫' },
  { country: 'BURUNDI', flag: '🇧🇮' },
  { country: 'CAMBODIA', flag: '🇰🇭' },
  { country: 'CAMEROON', flag: '🇨🇲' },
  { country: 'CANADA', flag: '🇨🇦' },
  { country: 'CANARY_ISLANDS', flag: '🇮🇨' },
  { country: 'CAPE_VERDE', flag: '🇨🇻' },
  { country: 'CARIBBEAN_NETHERLANDS', flag: '🇧🇶' },
  { country: 'CAYMAN_ISLANDS', flag: '🇰🇾' },
  { country: 'CENTRAL_AFRICAN_REPUBLIC', flag: '🇨🇫' },
  { country: 'CHAD', flag: '🇹🇩' },
  { country: 'CHILE', flag: '🇨🇱' },
  { country: 'CHINA', flag: '🇨🇳' },
  { country: 'CHRISTMAS_ISLAND', flag: '🇨🇽' },
  { country: 'COCOS_ISLANDS', flag: '🇨🇨' },
  { country: 'COLOMBIA', flag: '🇨🇴' },
  { country: 'COMOROS', flag: '🇰🇲' },
  { country: 'CONGO', flag: '🇨🇬' },
  { country: 'DEMOCRATIC_REPUBLIC_OF_THE_CONGO', flag: '🇨🇩' },
  { country: 'COOK_ISLANDS', flag: '🇨🇰' },
  { country: 'COSTA_RICA', flag: '🇨🇷' },
  { country: "CÔTE_D'IVOIRE", flag: '🇨🇮' },
  { country: 'CROATIA', flag: '🇭🇷' },
  { country: 'CUBA', flag: '🇨🇺' },
  { country: 'CURAÇAO', flag: '🇨🇼' },
  { country: 'CYPRUS', flag: '🇨🇾' },
  { country: 'CZECH_REPUBLIC', flag: '🇨🇿' },
  { country: 'DENMARK', flag: '🇩🇰' },
  { country: 'DJIBOUTI', flag: '🇩🇯' },
  { country: 'DOMINICA', flag: '🇩🇲' },
  { country: 'DOMINICAN_REPUBLIC', flag: '🇩🇴' },
  { country: 'ECUADOR', flag: '🇪🇨' },
  { country: 'EGYPT', flag: '🇪🇬' },
  { country: 'EL_SALVADOR', flag: '🇸🇻' },
  { country: 'EQUATORIAL_GUINEA', flag: '🇬🇶' },
  { country: 'ERITREA', flag: '🇪🇷' },
  { country: 'ESTONIA', flag: '🇪🇪' },
  { country: 'ETHIOPIA', flag: '🇪🇹' },
  { country: 'EUROPEAN_UNION', flag: '🇪🇺' },
  { country: 'FALKLAND_ISLANDS', flag: '🇫🇰' },
  { country: 'FAROE_ISLANDS', flag: '🇫🇴' },
  { country: 'FIJI', flag: '🇫🇯' },
  { country: 'FINLAND', flag: '🇫🇮' },
  { country: 'FRANCE', flag: '🇫🇷' },
  { country: 'FRENCH_GUiana', flag: '🇬🇫' },
  { country: 'FRENCH_POLYNESIA', flag: '🇵🇫' },
  { country: 'FRENCH_SOUTHERN_TERRITORIES', flag: '🇹🇫' },
  { country: 'GABON', flag: '🇬🇦' },
  { country: 'GAMBIA', flag: '🇬🇲' },
  { country: 'GEORGIA', flag: '🇬🇪' },
  { country: 'GERMANY', flag: '🇩🇪' },
  { country: 'GHANA', flag: '🇬🇭' },
  { country: 'GIBRALTAR', flag: '🇬🇮' },
  { country: 'GREECE', flag: '🇬🇷' },
  { country: 'GREENLAND', flag: '🇬🇱' },
  { country: 'GRENADA', flag: '🇬🇩' },
  { country: 'GUADELOUPE', flag: '🇬🇵' },
  { country: 'GUAM', flag: '🇬🇺' },
  { country: 'GUATEMALA', flag: '🇬🇹' },
  { country: 'GUERNSEY', flag: '🇬🇬' },
  { country: 'GUINEA', flag: '🇬🇳' },
  { country: 'GUINEA-BISSAU', flag: '🇬🇼' },
  { country: 'GUYANA', flag: '🇬🇾' },
  { country: 'HAITI', flag: '🇭🇹' },
  { country: 'HONDURAS', flag: '🇭🇳' },
  { country: 'HONG KONG', flag: '🇭🇰' },
  { country: 'HUNGARY', flag: '🇭🇺' },
  { country: 'ICELAND', flag: '🇮🇸' },
  { country: 'INDIA', flag: '🇮🇳' },
  { country: 'INDONESIA', flag: '🇮🇩' },
  { country: 'IRAN', flag: '🇮🇷' },
  { country: 'IRAQ', flag: '🇮🇶' },
  { country: 'IRELAND', flag: '🇮🇪' },
  { country: 'ISLE OF MAN', flag: '🇮🇲' },
  { country: 'ISRAEL', flag: '🇮🇱' },
  { country: 'ITALY', flag: '🇮🇹' },
  { country: 'JAMAICA', flag: '🇯🇲' },
  { country: 'JAPAN', flag: '🇯🇵' },
  { country: 'JERSEY', flag: '🇯🇪' },
  { country: 'JORDAN', flag: '🇯🇴' },
  { country: 'KAZAKHSTAN', flag: '🇰🇿' },
  { country: 'KENYA', flag: '🇰🇪' },
  { country: 'SOUTH KOREA', flag: '🇰🇷' },
  { country: 'KIRIBATI', flag: '🇰🇮' },
  { country: 'KOSOVO', flag: '🇽🇰' },
  { country: 'KUWAIT', flag: '🇰🇼' },
  { country: 'KYRGYZSTAN', flag: '🇰🇬' },
  { country: 'LAOS', flag: '🇱🇦' },
  { country: 'LATVIA', flag: '🇱🇻' },
  { country: 'LEBANON', flag: '🇱🇧' },
  { country: 'LESOTHO', flag: '🇱🇸' },
  { country: 'LIBERIA', flag: '🇱🇷' },
  { country: 'LIBYA', flag: '🇱🇾' },
  { country: 'LITHUANIA', flag: '🇱🇹' },
  { country: 'LUXEMBOURG', flag: '🇱🇺' },
  { country: 'MACAU', flag: '🇲🇴' },
  { country: 'NORTH MACEDONIA', flag: '🇲🇰' },
  { country: 'MADAGASCAR', flag: '🇲🇬' },
  { country: 'MALAWI', flag: '🇲🇼' },
  { country: 'MALAYSIA', flag: '🇲🇾' },
  { country: 'MALDIVES', flag: '🇲🇻' },
  { country: 'MALI', flag: '🇲🇱' },
  { country: 'MALTA', flag: '🇲🇹' },
  { country: 'MARSHALL ISLANDS', flag: '🇲🇭' },
  { country: 'MARTINIQUE', flag: '🇲🇶' },
  { country: 'MAURITANIA', flag: '🇲🇷' },
  { country: 'MAURITIUS', flag: '🇲🇺' },
  { country: 'MAYOTTE', flag: '🇾🇹' },
  { country: 'MEXICO', flag: '🇲🇽' },
  { country: 'MICRONESIA', flag: '🇫🇲' },
  { country: 'MOLDOVA', flag: '🇲🇩' },
  { country: 'MONACO', flag: '🇲🇨' },
  { country: 'MONGOLIA', flag: '🇲🇳' },
  { country: 'MONTENEGRO', flag: '🇲🇪' },
  { country: 'MONTSERRAT', flag: '🇲🇸' },
  { country: 'MOROCCO', flag: '🇲🇦' },
  { country: 'MOZAMBIQUE', flag: '🇲🇿' },
  { country: 'MYANMAR', flag: '🇲🇲' },
  { country: 'NAMIBIA', flag: '🇳🇦' },
  { country: 'NAURU', flag: '🇳🇷' },
  { country: 'NEPAL', flag: '🇳🇵' },
  { country: 'NETHERLANDS', flag: '🇳🇱' },
  { country: 'NEW CALEDONIA', flag: '🇳🇨' },
  { country: 'NEW ZEALAND', flag: '🇳🇿' },
  { country: 'NICARAGUA', flag: '🇳🇮' },
  { country: 'NIGER', flag: '🇳🇪' },
  { country: 'NIGERIA', flag: '🇳🇬' },
  { country: 'NIUE', flag: '🇳🇺' },
  { country: 'NORFOLK ISLAND', flag: '🇳🇫' },
  { country: 'NORTH KOREA', flag: '🇰🇵' },
  { country: 'NORTHERN MARIANA ISLANDS', flag: '🇲🇵' },
  { country: 'NORWAY', flag: '🇳🇴' },
  { country: 'OMAN', flag: '🇴🇲' },
  { country: 'PAKISTAN', flag: '🇵🇰' },
  { country: 'PALAU', flag: '🇵🇼' },
  { country: 'PALESTINE', flag: '🇵🇸' },
  { country: 'PANAMA', flag: '🇵🇦' },
  { country: 'PAPUA NEW GUINEA', flag: '🇵🇬' },
  { country: 'PARAGUAY', flag: '🇵🇾' },
  { country: 'PERU', flag: '🇵🇪' },
  { country: 'PHILIPPINES', flag: '🇵🇭' },
  { country: 'PITCAIRN ISLANDS', flag: '🇵🇳' },
  { country: 'POLAND', flag: '🇵🇱' },
  { country: 'PORTUGAL', flag: '🇵🇹' },
  { country: 'PUERTO RICO', flag: '🇵🇷' },
  { country: 'QATAR', flag: '🇶🇦' },
  { country: 'REUNION', flag: '🇷🇪' },
  { country: 'ROMANIA', flag: '🇷🇴' },
  { country: 'RUSSIA', flag: '🇷🇺' },
  { country: 'RWANDA', flag: '🇷🇼' },
  { country: 'SAMOA', flag: '🇼🇸' },
  { country: 'SAN MARINO', flag: '🇸🇲' },
  { country: 'SAUDI ARABIA', flag: '🇸🇦' },
  { country: 'SENEGAL', flag: '🇸🇳' },
  { country: 'SERBIA', flag: '🇷🇸' },
  { country: 'SEYCHELLES', flag: '🇸🇨' },
  { country: 'SIERRA LEONE', flag: '🇸🇱' },
  { country: 'SINGAPORE', flag: '🇸🇬' },
  { country: 'SINT MAARTEN', flag: '🇸🇽' },
  { country: 'SLOVAKIA', flag: '🇸🇰' },
  { country: 'SLOVENIA', flag: '🇸🇮' },
  { country: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', flag: '🇬🇸' },
  { country: 'SOUTH SUDAN', flag: '🇸🇧' },
  { country: 'SOMALIA', flag: '🇸🇴' },
  { country: 'SOUTH AFRICA', flag: '🇿🇦' },
  { country: 'SOUTH KOREA', flag: '🇰🇷' },
  { country: 'SOUTH SUDAN', flag: '🇸🇸' },
  { country: 'SPAIN', flag: '🇪🇸' },
  { country: 'SRI LANKA', flag: '🇱🇰' },
  { country: 'SAINT BARTHÉLEMY', flag: '🇧🇱' },
  { country: 'SAINT HELENA', flag: '🇸🇭' },
  { country: 'KINA', flag: '🇰🇳' },
  { country: 'LAOS', flag: '🇱🇨' },
  { country: 'SAINT PIERRE AND MIQUELON', flag: '🇵🇲' },
  { country: 'SAINT VINCENT AND THE GRENADINES', flag: '🇻🇨' },
  { country: 'SUDAN', flag: '🇸🇩' },
  { country: 'SURINAME', flag: '🇸🇷' },
  { country: 'SWAZILAND', flag: '🇸🇿' },
  { country: 'SWEDEN', flag: '🇸🇪' },
  { country: 'SWITZERLAND', flag: '🇨🇭' },
  { country: 'SYRIA', flag: '🇸🇾' },
  { country: 'TAIWAN', flag: '🇹🇼' },
  { country: 'TAJIKISTAN', flag: '🇹🇯' },
  { country: 'TANZANIA', flag: '🇹🇿' },
  { country: 'THAILAND', flag: '🇹🇭' },
  { country: 'TIMOR-LESTE', flag: '🇹🇱' },
  { country: 'TOGO', flag: '🇹🇬' },
  { country: 'TURKMENISTAN', flag: '🇹🇲' },
  { country: 'TURKS AND CAICOS ISLANDS', flag: '🇹🇨' },
  { country: 'TUVALU', flag: '🇹🇻' },
  { country: 'VIRGIN ISLANDS (US)', flag: '🇻🇮' },
  { country: 'UGANDA', flag: '🇺🇬' },
  { country: 'UKRAINE', flag: '🇺🇦' },
  { country: 'UNITED ARAB EMIRATES', flag: '🇦🇪' },
  { country: 'UNITED KINGDOM', flag: '🇬🇧' },
  { country: 'UNITED STATES', flag: '🇺🇸' },
  { country: 'URUGUAY', flag: '🇺🇾' },
  { country: 'UZBEKISTAN', flag: '🇺🇿' },
  { country: 'VANUATU', flag: '🇻🇺' },
  { country: 'VATICAN country', flag: '🇻🇦' },
  { country: 'VENEZUELA', flag: '🇻🇪' },
  { country: 'VIETNAM', flag: '🇻🇳' },
  { country: 'WALLIS AND FUTUNA', flag: '🇼🇫' },
  { country: 'WESTERN SAHARA', flag: '🇪🇭' },
  { country: 'YEMEN', flag: '🇾🇪' },
  { country: 'ZAMBIA', flag: '🇿🇲' },
  { country: 'ZIMBABWE', flag: '🇿🇼' },
];

export { flags };
